### ISSUE TITLE
high-res image / DNA to verify species identification; collection metadata (year, location, taxon interactions, co-occuring taxa)

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#429]
As a Researcher, Scientist I want to find out if a taxon has vanished from part of its geographic range / ecological niche so that I can think of causes, consequences, countermeasures for this I need high-res image / DNA to verify species identification; collection metadata (year, location, taxon interactions, co-occuring taxa)

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/285
