### ISSUE TITLE
interaction with various biological data publishing institutions and organisations,

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#516]
As a Biodiversity Data Node Manager I want to a platform for the aggregation and retrieval of Biodiversity data (both collection and observation data) so that provide access to Biodiversity data and data analysis tools for this I need interaction with various biological data publishing institutions and organisations,

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/186
