### ISSUE TITLE
evidence that DiSSCo's activities align with (e.g.) Sustainable Development Goals

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#531]
As a Policy maker I want to find information on the contribution of DiSSCo to the international environmental policy agenda so that can justify national level investments in its operation for this I need evidence that DiSSCo's activities align with (e.g.) Sustainable Development Goals

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/211
