### ISSUE TITLE
not only information on the sample, but also on the status and reference on the access status (without legal doc scan in the www!)

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#540]
As a Researcher, Scientist I want to easily identify which genetic resources I can directly request from a natural history collection so that can fullfill my due diligence obligations under the EU ABS regulation when requesting tissue or DNA-samples from an ex-situ situation inside Europe for this I need not only information on the sample, but also on the status and reference on the access status (without legal doc scan in the www!)

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/317
