### ISSUE TITLE
to know existing amounts of collections, and amount of new material coming in. collection amount, status, condition, health. Also collection health information.

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#545]
As a Collection Manager, Director, Administrator I want to know the situation with collection amounts so that can plan ahead for future needs for new space and storage. for this I need to know existing amounts of collections, and amount of new material coming in. collection amount, status, condition, health. Also collection health information.

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/224
