### ISSUE TITLE
information about the location and status of specimens in museum collections.

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#547]
As a Exhibition Designer I want to be able to find the location of specimens and information about species so that can design and realise interesting and accurate exhibitions and if required, loan specimens from otgher institutions for this I need information about the location and status of specimens in museum collections.

**Comment by kodapei** [comment]
this could use a CH label

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/323
