### ISSUE TITLE
overview of comparable data (image, DNA sequence link, location, ...) for multiple specimens from taxonomic group

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#549]
As a Teacher I want to show morphological and genetic diversity within a taxon so that can explain basic concepts in evolution, systematics, taxonomy, ecology etc. for this I need overview of comparable data (image, DNA sequence link, location, ...) for multiple specimens from taxonomic group

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/325
