### ISSUE TITLE
species names, images, distributions, habitats, needs, behaviour, ecological niches, relationships

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#550]
As a Teacher I want to learn about the variety of life and the relationships among species and their environment so that teach my students that we are all inter-connected and that Homo sapiens is not the best species on Earth for this I need species names, images, distributions, habitats, needs, behaviour, ecological niches, relationships

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/330
