### ISSUE TITLE
(AI) algorithm based on a selection of geological specimens

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#599]
As a Scientist I want to generate an generate an artificial intelligence (AI) algorithm based on a selection of geological specimens so that I can run the algorithm on images of other institutes to verify identifications and recover further specimens
under my species concept for this I need an AI toolbox to generate the AI algorithm.

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/253
