### ISSUE TITLE
Verify the validity of a determination by inspecting the type material (mineral, fossil)

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#601]
As a Scientist I want to verify the validity of a determination by inspecting the type material for that mineral / fossil so that I can confirm the valid identity of a mineral / fossil for this I need high quality images with different views (dorsal, ventral, detail shots etc...) and the metadata for the type specimens.

**Comment by SvMering** [comment]
duplicate of https://github.com/DiSSCo/user-stories/issues/277
